package com.swamigallardo.blades.gonk;

import java.util.HashMap;

public class MapTranslator {
    public HashMap<String, String> getMapsList() throws IllegalArgumentException{
        HashMap<String, String> mapsValues = new HashMap<>();

        mapsValues.put("cor1c_con","Coruscant CQ - CW");
        mapsValues.put("cor1c_ctf","Coruscant CTF - CW");
        mapsValues.put("cor1g_con","Coruscant CQ - GCW");
        mapsValues.put("cor1g_ctf","Coruscant CTF - GCW");
        mapsValues.put("dag1c_con","Dagobah CQ - CW");
        mapsValues.put("dag1c_ctf","Dagobah CTF - CW");
        mapsValues.put("dag1g_con","Dagobah CQ - GCW");
        mapsValues.put("dag1g_ctf","Dagobah CTF - GCW");
        mapsValues.put("dea1c_1flag","Death Star CTF - CW");
        mapsValues.put("dea1c_con","Death Star CQ - CW");
        mapsValues.put("dea1g_1flag","Death Star CTF - GCW");
        mapsValues.put("dea1g_con","Death Star CQ - GCW");
        mapsValues.put("end1c_1flag","Endor CTF - CW");
        mapsValues.put("end1c_con","Endor CQ - CW");
        mapsValues.put("end1g_1flag","Endor CTF - GCW");
        mapsValues.put("end1g_con","Endor CQ - GCW");
        mapsValues.put("end1g_hunt","Endor Hunt - GCW");
        mapsValues.put("fel1c_1flag","Felucia CTF - CW");
        mapsValues.put("fel1c_con","Felucia CQ - CW");
        mapsValues.put("fel1g_1flag","Felucia CTF - GCW");
        mapsValues.put("fel1g_con","Felucia CQ - GCW");
        mapsValues.put("geo1c_con","Geonosis CQ - CW");
        mapsValues.put("geo1c_ctf","Geonosis CTF - CW");
        mapsValues.put("geo1c_hunt","Geonosis Hunt - CW");
        mapsValues.put("geo1g_con","Geonosis CQ - GCW");
        mapsValues.put("geo1g_ctf","Geonosis CTF - GCW");
        mapsValues.put("hot1c_1flag","Hoth CTF - CW");
        mapsValues.put("hot1c_con","Hoth CQ - CW");
        mapsValues.put("hot1g_1flag","Hoth CTF - GCW");
        mapsValues.put("hot1g_con","Hoth CQ - GCW");
        mapsValues.put("hot1g_hunt","Hoth Hunt - GCW");
        mapsValues.put("kam1c_1flag","Kamino CTF - CW");
        mapsValues.put("kam1c_con","Kamino CQ - CW");
        mapsValues.put("kam1g_1flag","Kamino CTF - GCW");
        mapsValues.put("kam1g_con","Kamino CQ - GCW");
        mapsValues.put("kas2c_con","Kashyyyk CQ - CW");
        mapsValues.put("kas2c_ctf","Kashyyyk CTF - CW");
        mapsValues.put("kas2c_hunt","Kashyyyk Hunt - CW");
        mapsValues.put("kas2g_con","Kashyyyk CQ - GCW");
        mapsValues.put("kas2g_ctf","Kashyyyk CTF - GCW");
        mapsValues.put("mus1c_con","Mustafar CQ - CW");
        mapsValues.put("mus1c_ctf","Mustafar CTF - CW");
        mapsValues.put("mus1g_con","Mustafar CQ - GCW");
        mapsValues.put("mus1g_ctf","Mustafar CTF - GCW");
        mapsValues.put("myg1c_con","Mygeeto CQ - CW");
        mapsValues.put("myg1c_ctf","Mygeeto CTF - CW");
        mapsValues.put("myg1g_con","Mygeeto CQ - GCW");
        mapsValues.put("myg1g_ctf","Mygeeto CTF - GCW");
        mapsValues.put("nab2c_con","Naboo CQ - CW");
        mapsValues.put("nab2c_ctf","Naboo CTF - CW");
        mapsValues.put("nab2c_hunt","Naboo Hunt - CW");
        mapsValues.put("nab2g_con","Naboo CQ - GCW");
        mapsValues.put("nab2g_ctf","Naboo CTF - GCW");
        mapsValues.put("pol1c_con","Polis Massa CQ - CW");
        mapsValues.put("pol1c_ctf","Polis Massa CTF - CW");
        mapsValues.put("pol1g_con","Polis Massa CQ - GCW");
        mapsValues.put("pol1g_ctf","Polis Massa CTF - GCW");
        mapsValues.put("tan1c_1flag","Tantive IV CTF - CW");
        mapsValues.put("tan1c_con","Tantive IV CQ - CW");
        mapsValues.put("tan1g_1flag","Tantive IV CTF - GCW");
        mapsValues.put("tan1g_con","Tantive IV CQ - GCW");
        mapsValues.put("tat2c_con","Mos Eisley CQ - CW");
        mapsValues.put("tat2c_ctf","Mos Eisley CTF - CW");
        mapsValues.put("tat2c_hunt","Mos Eisley Hunt - CW");
        mapsValues.put("tat2g_con","Mos Eisley CQ - GCW");
        mapsValues.put("tat2g_ctf","Mos Eisley CTF - GCW");
        mapsValues.put("tat2g_eli","Mos Eisley Assault - GCW");
        mapsValues.put("tat3c_1flag","Jabba's Palace CTF - CW");
        mapsValues.put("tat3c_con","Jabba's Palace CQ - CW");
        mapsValues.put("tat3g_1flag","Jabba's Palace CTF - GCW");
        mapsValues.put("tat3g_con","Jabba's Palace CQ - GCW");
        mapsValues.put("uta1c_1flag","Utapau CTF - CW");
        mapsValues.put("uta1c_con","Utapau CQ - CW");
        mapsValues.put("uta1g_1flag","Utapau CTF - GCW");
        mapsValues.put("uta1g_con","Utapau CQ - GCW");
        mapsValues.put("yav1c_1flag","Yavin 4 CTF - CW");
        mapsValues.put("yav1c_con","Yavin 4 CQ - CW");
        mapsValues.put("yav1g_1flag","Yavin 4 CTF - GCW");
        mapsValues.put("yav1g_con","Yavin 4 CQ - GCW");

        return mapsValues;
    }
}
